- as: bool
  proto: bool

- as: i8
  proto: int32

- as: Int8Array
  proto: bytes
  repeated: false

- as: i16
  proto: int32

- as: Int16Array
  proto: int32
  repeated: true

- as: i32
  proto: int32

- as: Int32Array
  proto: int32
  repeated: true

- as: i64
  proto: int64

- as: Int64Array
  proto: int64
  repeated: true

- as: isize
  proto: int64

- as: u8
  proto: uint32

- as: Uint8Array
  proto: bytes
  repeated: false

- as: u16
  proto: uint32

- as: Uint16Array
  proto: uint32
  repeated: true

- as: u32
  proto: uint32

- as: Uint32Array
  proto: uint32
  repeated: true

- as: u64
  proto: uint64

- as: Uint64Array
  proto: uint64
  repeated: true

- as: usize
  proto: uint64

- as: f32
  proto: float

- as: Float32Array
  proto: float
  repeated: true

- as: f64
  proto: double

- as: Float64Array
  proto: double
  repeated: true

- as: string
  proto: string

# bytes arrays are special cases because they map to bytes in protobuf
# so for the moment we handle them like a primitive type
- as: Array<i8>
  proto: bytes
  repeated: false
  serialize: "changetype<Uint8Array>(\\1)"
  deserialize: "changetype<Array<i8>>(response.value)"

- as: Array<u8>
  proto: bytes
  repeated: false

- as: i8[]
  proto: bytes
  repeated: false

- as: u8[]
  proto: bytes
  repeated: false
